telegrambots:
  bot-username: CartMasterProBot
  bot-token: ${BOT_TOKEN}
  bot-path: /webhook
  webhook-secret: ${WEBHOOK_SECRET}

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8081}
